FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY icon.svg  /usr/share/nginx/html/icon.svg
COPY api.js     /usr/share/nginx/html/api.js
EXPOSE 80
